services:
  bday:
    build: .
    ports:
      - 44018:44018
    environment:
      - DB_HOST=bday-mysql
      - DB_USER=dp
      - DB_PASSWORD=MyStrongPass4@DB
      - DB_DATABASE=rsvp_db
    depends_on:
      - bday-mysql
    volumes:
      - .:/app
    networks:
      - bday_app_network
      - nginxproxymanager_default
networks:
  bday_app_network:
    external: true
  nginxproxymanager_default:
    external: true
