services:
  bday:
    build: .
    ports:
      - 44018:44018
    environment:
      - DB_HOST=birthday-db-mysql-1
      - DB_USER=dp
      - DB_PASSWORD=MyStrongPass4@DB
      - DB_DATABASE=rsvp_db
    volumes:
      - .:/app
    networks:
      - bday_app_network
      - nginxproxymanager_default
networks:
  bday_app_network:
    driver: bridge
  nginxproxymanager_default:
    external: true
